// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VRMC_vrm.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VrmProtobuf {

  /// <summary>Holder for reflection information generated from VRMC_vrm.proto</summary>
  public static partial class VRMCVrmReflection {

    #region Descriptor
    /// <summary>File descriptor for VRMC_vrm.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VRMCVrmReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5WUk1DX3ZybS5wcm90bxILVnJtUHJvdG9idWYaCm1ldGEucHJvdG8aDmh1",
            "bWFub2lkLnByb3RvGhFmaXJzdFBlcnNvbi5wcm90bxoMbG9va0F0LnByb3Rv",
            "GhBibGVuZFNoYXBlLnByb3RvIukBCgdWUk1DVnJtEhMKC3NwZWNWZXJzaW9u",
            "GAEgASgJEh8KBG1ldGEYAiABKAsyES5Wcm1Qcm90b2J1Zi5NZXRhEicKCGh1",
            "bWFub2lkGAMgASgLMhUuVnJtUHJvdG9idWYuSHVtYW5vaWQSLQoLZmlyc3RQ",
            "ZXJzb24YBCABKAsyGC5Wcm1Qcm90b2J1Zi5GaXJzdFBlcnNvbhIjCgZsb29r",
            "QXQYBSABKAsyEy5Wcm1Qcm90b2J1Zi5Mb29rQXQSKwoKYmxlbmRTaGFwZRgG",
            "IAEoCzIXLlZybVByb3RvYnVmLkJsZW5kU2hhcGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::VrmProtobuf.MetaReflection.Descriptor, global::VrmProtobuf.HumanoidReflection.Descriptor, global::VrmProtobuf.FirstPersonReflection.Descriptor, global::VrmProtobuf.LookAtReflection.Descriptor, global::VrmProtobuf.BlendShapeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VrmProtobuf.VRMCVrm), global::VrmProtobuf.VRMCVrm.Parser, new[]{ "SpecVersion", "Meta", "Humanoid", "FirstPerson", "LookAt", "BlendShape" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class VRMCVrm : pb::IMessage<VRMCVrm> {
    private static readonly pb::MessageParser<VRMCVrm> _parser = new pb::MessageParser<VRMCVrm>(() => new VRMCVrm());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VRMCVrm> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VrmProtobuf.VRMCVrmReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VRMCVrm() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VRMCVrm(VRMCVrm other) : this() {
      specVersion_ = other.specVersion_;
      meta_ = other.meta_ != null ? other.meta_.Clone() : null;
      humanoid_ = other.humanoid_ != null ? other.humanoid_.Clone() : null;
      firstPerson_ = other.firstPerson_ != null ? other.firstPerson_.Clone() : null;
      lookAt_ = other.lookAt_ != null ? other.lookAt_.Clone() : null;
      blendShape_ = other.blendShape_ != null ? other.blendShape_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VRMCVrm Clone() {
      return new VRMCVrm(this);
    }

    /// <summary>Field number for the "specVersion" field.</summary>
    public const int SpecVersionFieldNumber = 1;
    private string specVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SpecVersion {
      get { return specVersion_; }
      set {
        specVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "meta" field.</summary>
    public const int MetaFieldNumber = 2;
    private global::VrmProtobuf.Meta meta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VrmProtobuf.Meta Meta {
      get { return meta_; }
      set {
        meta_ = value;
      }
    }

    /// <summary>Field number for the "humanoid" field.</summary>
    public const int HumanoidFieldNumber = 3;
    private global::VrmProtobuf.Humanoid humanoid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VrmProtobuf.Humanoid Humanoid {
      get { return humanoid_; }
      set {
        humanoid_ = value;
      }
    }

    /// <summary>Field number for the "firstPerson" field.</summary>
    public const int FirstPersonFieldNumber = 4;
    private global::VrmProtobuf.FirstPerson firstPerson_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VrmProtobuf.FirstPerson FirstPerson {
      get { return firstPerson_; }
      set {
        firstPerson_ = value;
      }
    }

    /// <summary>Field number for the "lookAt" field.</summary>
    public const int LookAtFieldNumber = 5;
    private global::VrmProtobuf.LookAt lookAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VrmProtobuf.LookAt LookAt {
      get { return lookAt_; }
      set {
        lookAt_ = value;
      }
    }

    /// <summary>Field number for the "blendShape" field.</summary>
    public const int BlendShapeFieldNumber = 6;
    private global::VrmProtobuf.BlendShape blendShape_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VrmProtobuf.BlendShape BlendShape {
      get { return blendShape_; }
      set {
        blendShape_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VRMCVrm);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VRMCVrm other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SpecVersion != other.SpecVersion) return false;
      if (!object.Equals(Meta, other.Meta)) return false;
      if (!object.Equals(Humanoid, other.Humanoid)) return false;
      if (!object.Equals(FirstPerson, other.FirstPerson)) return false;
      if (!object.Equals(LookAt, other.LookAt)) return false;
      if (!object.Equals(BlendShape, other.BlendShape)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SpecVersion.Length != 0) hash ^= SpecVersion.GetHashCode();
      if (meta_ != null) hash ^= Meta.GetHashCode();
      if (humanoid_ != null) hash ^= Humanoid.GetHashCode();
      if (firstPerson_ != null) hash ^= FirstPerson.GetHashCode();
      if (lookAt_ != null) hash ^= LookAt.GetHashCode();
      if (blendShape_ != null) hash ^= BlendShape.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SpecVersion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SpecVersion);
      }
      if (meta_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Meta);
      }
      if (humanoid_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Humanoid);
      }
      if (firstPerson_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FirstPerson);
      }
      if (lookAt_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LookAt);
      }
      if (blendShape_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(BlendShape);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SpecVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SpecVersion);
      }
      if (meta_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Meta);
      }
      if (humanoid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Humanoid);
      }
      if (firstPerson_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FirstPerson);
      }
      if (lookAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LookAt);
      }
      if (blendShape_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BlendShape);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VRMCVrm other) {
      if (other == null) {
        return;
      }
      if (other.SpecVersion.Length != 0) {
        SpecVersion = other.SpecVersion;
      }
      if (other.meta_ != null) {
        if (meta_ == null) {
          Meta = new global::VrmProtobuf.Meta();
        }
        Meta.MergeFrom(other.Meta);
      }
      if (other.humanoid_ != null) {
        if (humanoid_ == null) {
          Humanoid = new global::VrmProtobuf.Humanoid();
        }
        Humanoid.MergeFrom(other.Humanoid);
      }
      if (other.firstPerson_ != null) {
        if (firstPerson_ == null) {
          FirstPerson = new global::VrmProtobuf.FirstPerson();
        }
        FirstPerson.MergeFrom(other.FirstPerson);
      }
      if (other.lookAt_ != null) {
        if (lookAt_ == null) {
          LookAt = new global::VrmProtobuf.LookAt();
        }
        LookAt.MergeFrom(other.LookAt);
      }
      if (other.blendShape_ != null) {
        if (blendShape_ == null) {
          BlendShape = new global::VrmProtobuf.BlendShape();
        }
        BlendShape.MergeFrom(other.BlendShape);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SpecVersion = input.ReadString();
            break;
          }
          case 18: {
            if (meta_ == null) {
              Meta = new global::VrmProtobuf.Meta();
            }
            input.ReadMessage(Meta);
            break;
          }
          case 26: {
            if (humanoid_ == null) {
              Humanoid = new global::VrmProtobuf.Humanoid();
            }
            input.ReadMessage(Humanoid);
            break;
          }
          case 34: {
            if (firstPerson_ == null) {
              FirstPerson = new global::VrmProtobuf.FirstPerson();
            }
            input.ReadMessage(FirstPerson);
            break;
          }
          case 42: {
            if (lookAt_ == null) {
              LookAt = new global::VrmProtobuf.LookAt();
            }
            input.ReadMessage(LookAt);
            break;
          }
          case 50: {
            if (blendShape_ == null) {
              BlendShape = new global::VrmProtobuf.BlendShape();
            }
            input.ReadMessage(BlendShape);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
