// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VRMC_springBone.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VrmProtobuf {

  /// <summary>Holder for reflection information generated from VRMC_springBone.proto</summary>
  public static partial class VRMCSpringBoneReflection {

    #region Descriptor
    /// <summary>File descriptor for VRMC_springBone.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VRMCSpringBoneReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVWUk1DX3NwcmluZ0JvbmUucHJvdG8SC1ZybVByb3RvYnVmGh5nb29nbGUv",
            "cHJvdG9idWYvd3JhcHBlcnMucHJvdG8itgEKDVNwcmluZ1NldHRpbmcSLgoJ",
            "c3RpZmZuZXNzGAEgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkZsb2F0VmFsdWUS",
            "MQoMZ3Jhdml0eVBvd2VyGAIgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkZsb2F0",
            "VmFsdWUSEgoKZ3Jhdml0eURpchgDIAMoAhIuCglkcmFnRm9yY2UYBCABKAsy",
            "Gy5nb29nbGUucHJvdG9idWYuRmxvYXRWYWx1ZSK4AQoGU3ByaW5nEgwKBG5h",
            "bWUYASABKAkSLAoHc2V0dGluZxgCIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5J",
            "bnQzMlZhbHVlEi8KCnNwcmluZ1Jvb3QYAyABKAsyGy5nb29nbGUucHJvdG9i",
            "dWYuSW50MzJWYWx1ZRIuCgloaXRSYWRpdXMYBCABKAsyGy5nb29nbGUucHJv",
            "dG9idWYuRmxvYXRWYWx1ZRIRCgljb2xsaWRlcnMYBSADKAUiZAoOVlJNQ1Nw",
            "cmluZ0JvbmUSLAoIc2V0dGluZ3MYASADKAsyGi5Wcm1Qcm90b2J1Zi5TcHJp",
            "bmdTZXR0aW5nEiQKB3NwcmluZ3MYAiADKAsyEy5Wcm1Qcm90b2J1Zi5TcHJp",
            "bmdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VrmProtobuf.SpringSetting), global::VrmProtobuf.SpringSetting.Parser, new[]{ "Stiffness", "GravityPower", "GravityDir", "DragForce" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VrmProtobuf.Spring), global::VrmProtobuf.Spring.Parser, new[]{ "Name", "Setting", "SpringRoot", "HitRadius", "Colliders" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VrmProtobuf.VRMCSpringBone), global::VrmProtobuf.VRMCSpringBone.Parser, new[]{ "Settings", "Springs" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SpringSetting : pb::IMessage<SpringSetting> {
    private static readonly pb::MessageParser<SpringSetting> _parser = new pb::MessageParser<SpringSetting>(() => new SpringSetting());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SpringSetting> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VrmProtobuf.VRMCSpringBoneReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpringSetting() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpringSetting(SpringSetting other) : this() {
      Stiffness = other.Stiffness;
      GravityPower = other.GravityPower;
      gravityDir_ = other.gravityDir_.Clone();
      DragForce = other.DragForce;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpringSetting Clone() {
      return new SpringSetting(this);
    }

    /// <summary>Field number for the "stiffness" field.</summary>
    public const int StiffnessFieldNumber = 1;
    private static readonly pb::FieldCodec<float?> _single_stiffness_codec = pb::FieldCodec.ForStructWrapper<float>(10);
    private float? stiffness_;
    /// <summary>
    /// The force to return to the initial pose
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float? Stiffness {
      get { return stiffness_; }
      set {
        stiffness_ = value;
      }
    }


    /// <summary>Field number for the "gravityPower" field.</summary>
    public const int GravityPowerFieldNumber = 2;
    private static readonly pb::FieldCodec<float?> _single_gravityPower_codec = pb::FieldCodec.ForStructWrapper<float>(18);
    private float? gravityPower_;
    /// <summary>
    /// Gravitational acceleration
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float? GravityPower {
      get { return gravityPower_; }
      set {
        gravityPower_ = value;
      }
    }


    /// <summary>Field number for the "gravityDir" field.</summary>
    public const int GravityDirFieldNumber = 3;
    private static readonly pb::FieldCodec<float> _repeated_gravityDir_codec
        = pb::FieldCodec.ForFloat(26);
    private readonly pbc::RepeatedField<float> gravityDir_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// The direction of gravity. A gravity other than downward direction also works.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> GravityDir {
      get { return gravityDir_; }
    }

    /// <summary>Field number for the "dragForce" field.</summary>
    public const int DragForceFieldNumber = 4;
    private static readonly pb::FieldCodec<float?> _single_dragForce_codec = pb::FieldCodec.ForStructWrapper<float>(34);
    private float? dragForce_;
    /// <summary>
    /// Air resistance. Deceleration force
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float? DragForce {
      get { return dragForce_; }
      set {
        dragForce_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SpringSetting);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SpringSetting other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.Equals(Stiffness, other.Stiffness)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.Equals(GravityPower, other.GravityPower)) return false;
      if(!gravityDir_.Equals(other.gravityDir_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.Equals(DragForce, other.DragForce)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (stiffness_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.GetHashCode(Stiffness);
      if (gravityPower_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.GetHashCode(GravityPower);
      hash ^= gravityDir_.GetHashCode();
      if (dragForce_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.GetHashCode(DragForce);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (stiffness_ != null) {
        _single_stiffness_codec.WriteTagAndValue(output, Stiffness);
      }
      if (gravityPower_ != null) {
        _single_gravityPower_codec.WriteTagAndValue(output, GravityPower);
      }
      gravityDir_.WriteTo(output, _repeated_gravityDir_codec);
      if (dragForce_ != null) {
        _single_dragForce_codec.WriteTagAndValue(output, DragForce);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (stiffness_ != null) {
        size += _single_stiffness_codec.CalculateSizeWithTag(Stiffness);
      }
      if (gravityPower_ != null) {
        size += _single_gravityPower_codec.CalculateSizeWithTag(GravityPower);
      }
      size += gravityDir_.CalculateSize(_repeated_gravityDir_codec);
      if (dragForce_ != null) {
        size += _single_dragForce_codec.CalculateSizeWithTag(DragForce);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SpringSetting other) {
      if (other == null) {
        return;
      }
      if (other.stiffness_ != null) {
        if (stiffness_ == null || other.Stiffness != 0F) {
          Stiffness = other.Stiffness;
        }
      }
      if (other.gravityPower_ != null) {
        if (gravityPower_ == null || other.GravityPower != 0F) {
          GravityPower = other.GravityPower;
        }
      }
      gravityDir_.Add(other.gravityDir_);
      if (other.dragForce_ != null) {
        if (dragForce_ == null || other.DragForce != 0F) {
          DragForce = other.DragForce;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            float? value = _single_stiffness_codec.Read(input);
            if (stiffness_ == null || value != 0F) {
              Stiffness = value;
            }
            break;
          }
          case 18: {
            float? value = _single_gravityPower_codec.Read(input);
            if (gravityPower_ == null || value != 0F) {
              GravityPower = value;
            }
            break;
          }
          case 26:
          case 29: {
            gravityDir_.AddEntriesFrom(input, _repeated_gravityDir_codec);
            break;
          }
          case 34: {
            float? value = _single_dragForce_codec.Read(input);
            if (dragForce_ == null || value != 0F) {
              DragForce = value;
            }
            break;
          }
        }
      }
    }

  }

  public sealed partial class Spring : pb::IMessage<Spring> {
    private static readonly pb::MessageParser<Spring> _parser = new pb::MessageParser<Spring>(() => new Spring());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Spring> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VrmProtobuf.VRMCSpringBoneReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Spring() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Spring(Spring other) : this() {
      name_ = other.name_;
      Setting = other.Setting;
      SpringRoot = other.SpringRoot;
      HitRadius = other.HitRadius;
      colliders_ = other.colliders_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Spring Clone() {
      return new Spring(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// Name of the Spring
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "setting" field.</summary>
    public const int SettingFieldNumber = 2;
    private static readonly pb::FieldCodec<int?> _single_setting_codec = pb::FieldCodec.ForStructWrapper<int>(18);
    private int? setting_;
    /// <summary>
    /// The index of spring settings
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int? Setting {
      get { return setting_; }
      set {
        setting_ = value;
      }
    }


    /// <summary>Field number for the "springRoot" field.</summary>
    public const int SpringRootFieldNumber = 3;
    private static readonly pb::FieldCodec<int?> _single_springRoot_codec = pb::FieldCodec.ForStructWrapper<int>(26);
    private int? springRoot_;
    /// <summary>
    /// The node index of spring root
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int? SpringRoot {
      get { return springRoot_; }
      set {
        springRoot_ = value;
      }
    }


    /// <summary>Field number for the "hitRadius" field.</summary>
    public const int HitRadiusFieldNumber = 4;
    private static readonly pb::FieldCodec<float?> _single_hitRadius_codec = pb::FieldCodec.ForStructWrapper<float>(34);
    private float? hitRadius_;
    /// <summary>
    /// The radius of spring sphere
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float? HitRadius {
      get { return hitRadius_; }
      set {
        hitRadius_ = value;
      }
    }


    /// <summary>Field number for the "colliders" field.</summary>
    public const int CollidersFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_colliders_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> colliders_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// Colliders that detect collision with nodes start from springRoot
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Colliders {
      get { return colliders_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Spring);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Spring other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Setting != other.Setting) return false;
      if (SpringRoot != other.SpringRoot) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.Equals(HitRadius, other.HitRadius)) return false;
      if(!colliders_.Equals(other.colliders_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (setting_ != null) hash ^= Setting.GetHashCode();
      if (springRoot_ != null) hash ^= SpringRoot.GetHashCode();
      if (hitRadius_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.GetHashCode(HitRadius);
      hash ^= colliders_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (setting_ != null) {
        _single_setting_codec.WriteTagAndValue(output, Setting);
      }
      if (springRoot_ != null) {
        _single_springRoot_codec.WriteTagAndValue(output, SpringRoot);
      }
      if (hitRadius_ != null) {
        _single_hitRadius_codec.WriteTagAndValue(output, HitRadius);
      }
      colliders_.WriteTo(output, _repeated_colliders_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (setting_ != null) {
        size += _single_setting_codec.CalculateSizeWithTag(Setting);
      }
      if (springRoot_ != null) {
        size += _single_springRoot_codec.CalculateSizeWithTag(SpringRoot);
      }
      if (hitRadius_ != null) {
        size += _single_hitRadius_codec.CalculateSizeWithTag(HitRadius);
      }
      size += colliders_.CalculateSize(_repeated_colliders_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Spring other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.setting_ != null) {
        if (setting_ == null || other.Setting != 0) {
          Setting = other.Setting;
        }
      }
      if (other.springRoot_ != null) {
        if (springRoot_ == null || other.SpringRoot != 0) {
          SpringRoot = other.SpringRoot;
        }
      }
      if (other.hitRadius_ != null) {
        if (hitRadius_ == null || other.HitRadius != 0F) {
          HitRadius = other.HitRadius;
        }
      }
      colliders_.Add(other.colliders_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            int? value = _single_setting_codec.Read(input);
            if (setting_ == null || value != 0) {
              Setting = value;
            }
            break;
          }
          case 26: {
            int? value = _single_springRoot_codec.Read(input);
            if (springRoot_ == null || value != 0) {
              SpringRoot = value;
            }
            break;
          }
          case 34: {
            float? value = _single_hitRadius_codec.Read(input);
            if (hitRadius_ == null || value != 0F) {
              HitRadius = value;
            }
            break;
          }
          case 42:
          case 40: {
            colliders_.AddEntriesFrom(input, _repeated_colliders_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class VRMCSpringBone : pb::IMessage<VRMCSpringBone> {
    private static readonly pb::MessageParser<VRMCSpringBone> _parser = new pb::MessageParser<VRMCSpringBone>(() => new VRMCSpringBone());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VRMCSpringBone> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VrmProtobuf.VRMCSpringBoneReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VRMCSpringBone() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VRMCSpringBone(VRMCSpringBone other) : this() {
      settings_ = other.settings_.Clone();
      springs_ = other.springs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VRMCSpringBone Clone() {
      return new VRMCSpringBone(this);
    }

    /// <summary>Field number for the "settings" field.</summary>
    public const int SettingsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::VrmProtobuf.SpringSetting> _repeated_settings_codec
        = pb::FieldCodec.ForMessage(10, global::VrmProtobuf.SpringSetting.Parser);
    private readonly pbc::RepeatedField<global::VrmProtobuf.SpringSetting> settings_ = new pbc::RepeatedField<global::VrmProtobuf.SpringSetting>();
    /// <summary>
    /// An array of settings.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::VrmProtobuf.SpringSetting> Settings {
      get { return settings_; }
    }

    /// <summary>Field number for the "springs" field.</summary>
    public const int SpringsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::VrmProtobuf.Spring> _repeated_springs_codec
        = pb::FieldCodec.ForMessage(18, global::VrmProtobuf.Spring.Parser);
    private readonly pbc::RepeatedField<global::VrmProtobuf.Spring> springs_ = new pbc::RepeatedField<global::VrmProtobuf.Spring>();
    /// <summary>
    /// An array of springs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::VrmProtobuf.Spring> Springs {
      get { return springs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VRMCSpringBone);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VRMCSpringBone other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!settings_.Equals(other.settings_)) return false;
      if(!springs_.Equals(other.springs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= settings_.GetHashCode();
      hash ^= springs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      settings_.WriteTo(output, _repeated_settings_codec);
      springs_.WriteTo(output, _repeated_springs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += settings_.CalculateSize(_repeated_settings_codec);
      size += springs_.CalculateSize(_repeated_springs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VRMCSpringBone other) {
      if (other == null) {
        return;
      }
      settings_.Add(other.settings_);
      springs_.Add(other.springs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            settings_.AddEntriesFrom(input, _repeated_settings_codec);
            break;
          }
          case 18: {
            springs_.AddEntriesFrom(input, _repeated_springs_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
